<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
     <PackageId>AgentSim.Core</PackageId>
    <Version>1.0.0</Version>
    <Authors>AgentSim Studio Team</Authors>
    <Description>Reusable agent-based modelling engine with Roslyn scripting support</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0" />
  </ItemGroup>

</Project>
